ACCOUNT_ID?=MY_AWS_ACCOUNT_ID
DOCKER_REGISTRY?=$(ACCOUNT_ID).dkr.ecr.us-west-2.amazonaws.com/$(SERVICE_NAME)

.PHONY: build
build:
	docker build -t $(SERVICE_NAME) .

.PHONY: publish 
publish: build
	docker tag $(SERVICE_NAME) $(DOCKER_REGISTRY)
	docker push $(DOCKER_REGISTRY)

.PHONY: deploy
deploy: publish
	kubectl apply -f k8s.yaml
	kubectl rollout restart deployment/$(SERVICE_NAME)
