apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srv-search 
  name: srv-search
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv-search
  template:
    metadata:
      labels:
        app: srv-search
    spec:
      containers:
      - image: MY_AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/srv-search:latest
        name: srv-search
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SPLK_TRACE_EXPORTER_URL
            value: "http://$(NODE_IP):9080/v1/trace"
          - name: SPLK_SERVICE_NAME
            value: srv-search
---
apiVersion: v1
kind: Service
metadata:
  name: srv-search
  labels:
    app: srv-search
spec:
  ports:
  - name: http 
    port: 8001
  selector:
    app: srv-search